apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-l4ilcofjeimlz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-l4ilcofjeimlz
    app.kubernetes.io/part-of: test-gitlabrenovate-c5jg8edxezxdg
  name: component-l4ilcofjeimlz
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-l4ilcofjeimlz
status:
  loadBalancer: {}
